### ISSUE TITLE
Winrunner doesn't build with latest commit

### ISSUE THREAD

**Issue by svrc** [IronFoundry/if_release#12]
Trying with Go 1.4.1 on Win2012... probably the build.ps1 needs an update to compile the dependent library

GOPATH=C:\github\ironfoundry\if\if_release\dea_ng\go

C:\github\ironfoundry\if\if_release>go build winrunner
# code.google.com/p/winsvc/svc
svc\event.go:22: undefined: winapi.CreateEvent
svc\event.go:34: undefined: winapi.SetEvent
svc\security.go:47: undefined: winapi.AllocateAndInitializeSid
svc\security.go:63: undefined: winapi.FreeSid
svc\security.go:69: undefined: winapi.FreeSid
svc\security.go:84: undefined: winapi.EqualSid
svc\security.go:87: undefined: winapi.EqualSid
svc\service.go:178: undefined: winapi.SetServiceStatus
svc\service.go:270: undefined: winapi.GetCurrentThreadId
svc\service.go:284: undefined: winapi.GetCurrentThreadId
svc\service.go:284: too many errors
# code.google.com/p/winsvc/registry
registry\registry.go:39: undefined: winapi.RegCreateKeyEx
registry\registry.go:50: undefined: winapi.RegDeleteKey
registry\registry.go:54: undefined: winapi.RegSetValueEx
registry\registry.go:62: undefined: winapi.RegSetValueEx

**Comment by mosoto** [comment]
Some files were missing. Should be fixed now. Thanks!
