### ISSUE TITLE
IIS log files are not being created.  Warden_User_* accounts don't have sufficient file permissions.

### ISSUE THREAD

**Issue by jmprice** [IronFoundry/if_release#13]
The warden_user account created for each container doesn't have the file permissions needed to create the IIS logs files in the \user\app\.iishost\log\IIS\.

Windows System Log:
Log Name:      System
Source:        Microsoft-Windows-HttpEvent
Date:          2/19/2015 10:55:12 AM
Event ID:      15001
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      FM7-WINDEA01.amr.corp.intel.com
Description:
Unable to create the log file for site W3SVC0. Make sure that the logging directory for the site is correct and this computer has write access to that directory.

Failure captured by Procmon.exe:

Date & Time:	2/19/2015 10:55:12 AM
Event Class:	File System
Operation:	IRP_MJ_CREATE
Result:	ACCESS DENIED
Path:	D:\IronFoundry\warden\containers\21DE2BD77BBD3770A4
TID:	2280
Duration:	0.0000429
Desired Access:	Read Data/List Directory, Execute/Traverse
Disposition:	OpenIf
Options:	Directory
Attributes:	N
ShareMode:	Read
AllocationSize:	0
Impersonating:	TEST-WINDEA01\c_21DE2BD77BBD3770A4

Jon Price
Intel Corporation

**Comment by csterwa** [comment]
@jmprice sorry for not getting back to you sooner. Just a few hours ago @mosoto put in a fix for this issue. Would you be able to pull your if_release again and try again? Let us know if this fix worked for you.

BTW. Sorry for the delay in my response. I was on vacation for a week and did not see this issue come in. I will make sure to get back to you sooner in the future. Thanks.

**Comment by mosoto** [comment]
@csterwa @jmprice The fix isn't yet into master though it will be soon.

**Comment by csterwa** [comment]
Oops @jmprice - I spoke too soon. Thanks, @mosoto

**Comment by jmprice** [comment]
@mosoto Any estimate as to when this fix may hit the master branch?

**Comment by jmprice** [comment]
ping

**Comment by mosoto** [comment]
Hey Jon, I'll merge it in the next 2-3 days.

**Comment by jmprice** [comment]
Awesome! Thank you very much!

**Comment by mosoto** [comment]
That should fix it.  Let me know if you still can't get the IIS logs.

**Comment by jmprice** [comment]
@mosoto Everything looks great!  Thank you very much. :)
