### ISSUE TITLE
cannot build a release

### ISSUE THREAD

**Issue by yzzhu** [IronFoundry/if_release#15]
Followed the step of 
https://github.com/IronFoundry/if_release#build-release-on-dev-machine
the only different thing it that I use a windows 2008 server 64bit as the dev-machine,. when I execute build.ps1, it shows as below:

PS C:\projects\if_release> .\build.ps1
Updating submodules
Synchronizing submodule url for 'dea_ng'
Synchronizing submodule url for 'dea_ng/go/src/github.com/cloudfoundry/gosteno'
Synchronizing submodule url for 'dea_ng/go/src/github.com/howeyc/fsnotify'
Synchronizing submodule url for 'eventmachine'
Synchronizing submodule url for 'if_warden'
Synchronizing submodule url for 'if_warden/IronFoundry.Warden.Protocol/warden'
Synchronizing submodule url for 'if_warden/IronFrame'
Building Warden: 0.0.0
  Restoring packages from NuGet...
  IronFrame.Shared -> C:\projects\if_release\if_warden\IronFrame\IronFrame.Shared\bin\Release\IronFrame.Shared.dll
  IronFrame.TestHelper -> C:\projects\if_release\if_warden\IronFrame\IronFrame.TestHelper\bin\Release\IFTestHelper.exe
  IronFrame.Host -> C:\projects\if_release\if_warden\IronFrame\IronFrame.Host\bin\Release\IronFrame.Host.exe
  IronFrame -> C:\projects\if_release\if_warden\IronFrame\IronFrame\bin\Release\IronFrame.dll
  IronFrame.Test -> C:\projects\if_release\if_warden\IronFrame\IronFrame.Test\bin\Release\IronFrame.Test.dll
  IronFrame.Acceptance.Test -> C:\projects\if_release\if_warden\IronFrame\IronFrame.Acceptance.Test\bin\Release\IronFra
  me.Acceptance.Test.dll
  xUnit.net MSBuild runner (64-bit .NET 4.0.30319.18408)
    Discovering: IronFrame.Acceptance.Test
    Discovered:  IronFrame.Acceptance.Test
    Starting:    IronFrame.Acceptance.Test

here it pops a console, and then waiting here without any tips for a long time, I am not sure whether it's something running backend or it faied?

1. the question is whether the  windows 2008 server 64bit as the dev-machine is OK? 
2. how long it will take to build the release normally?

**Comment by brannon** [comment]
@yzzhu IronFoundry requires Windows Server 2012 (or Windows 8). The container library uses security features that are not available in Windows 2008.

**Comment by yzzhu** [comment]
@brannon  Do you mean that even build the ironfoundry release need win2012 or win8？and then run the release on win2012 server?

**Comment by brannon** [comment]
The build runs the test suite, which will fail on 2008. If you see a console window popping up, that's most likely what's happening. I don't know why the build hangs vs. failing with an error. We don't run it on 2008 anymore.

If you are just trying to get a set of binaries that you can install on a server, I can check to see if we have a set of prebuilt binaries available.

**Comment by yzzhu** [comment]
I want to integrate ironfoundry to my cf environment. It's a great help if you can privide me the binaries, thanks a lot!
